### ISSUE TITLE
rfield / rhash and str.isdigit()

### ISSUE THREAD

**Issue by anton62k** [dsociative/rmodel#2]
Неплохо бы убрать автоматическое преобразование явно заданного типа str в rhash / rhash в int.
Например, задаем uid = rfield(str, ""). Если записываем скажем "1234560", то при чтение получаем int.
Неприятные моменты в практике уже были с этим.

https://github.com/Disassociative/rmodel/blob/master/rmodel.py#L51

**Comment by dsociative** [comment]
Да, старый хак, нужно подчистить это момент. Думаю, оставить это для не указанной типизации , например

```
field1 = rfield(default="field_name1")
field1.get()
>>> "field_name1"
field.set(1)
field.get()
>>> 1
```

**Comment by anton62k** [comment]
Да, хорошая идея оставить для не указанной типизации.

**Comment by dsociative** [comment]
done
