### ISSUE TITLE
Сhanges data

### ISSUE THREAD

**Issue by dsociative** [dsociative/rmodel#4]

**Comment by anton62k** [comment]
1. Думаю, что выдачу только "измененных" данных надо сделать отдельным методом или с помощью параметра, которые по умолчанию False).
2. в случае с "добавленными" или "измененными" данными примерно ясно как они должны выглядеть. но как выводить удаленные подмодели или ключи в rhash?

**Comment by dsociative** [comment]
- Да, будет отдельный метод и скорее всего отдельная опция. Так как включатся специализированный кешинг дерева для будущей выдачи изменений без обращений к базе.
- Добавленные и измененные ключи будут выглядеть одинаково, если в rhash поменяется значение, то в его changes будет `{'field': 'new_value'}`.
- Для удаленных полей(RModel и ко тоже поля по сути) в changes родителя будет добавлятся специальный ключ со списком удаленных ключей, например `{'_rm':['1', '2']}`. Для айтемов RModelStore предок RModelStore, для поля в rhash предок rhash и т.д.

**Comment by anton62k** [comment]
Было еще одно неудобство с data() методом. 

В некоторой модели есть "простые" поля rfield, rhash, но также есть и подмодели. задача была выдавать только простые поля модели, без подмоделей. так как этой возможности не было, приходилось выдавать лишние данные. Это наверное надо решать архитектурой моделей?

Возможно нужны какие то фильтры при выдаче. Т.е. "рекурсивно" или нет, все поля или только список.

**Comment by dsociative** [comment]
Да, лучше всего архитектурно решать подобные вопросы, либо писать хаки типа:

```
    def only_current_model_data(self):
        pipe = self.redis.pipeline()

        for field in self.fields():
            if is_in_current_model(field):
                field.data(pipe, key=self.cursor.key)

            return self.process_data(pipe.execute())
```

Дело в том что в data() опрашиваются данные не по-модельно, а в порядке очереди в глобальном контексте, поэтому если что-то посчитать не верно или фильтр лажанет - данные побьются.
